/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.41
 * Generated at: 2017-05-06 16:26:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.frontend;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.library.Utilities;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.library.Utilities");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String productDetailImg = (String) session.getAttribute("productDetailImg");
	String productDetailName = (String) session.getAttribute("productDetailName");
	String productDetailPrefix = (String) session.getAttribute("productDetailPrefix");
	int productDetailPrice = (int) session.getAttribute("productDetailPrice");
	String productDetailWarranty = (String) session.getAttribute("productDetailWarranty");
	String productDetailSummary = (String) session.getAttribute("productDetailSummary");
	String productDetailContent = (String) session.getAttribute("productDetailContent");
	String product_id = (String) session.getAttribute("product_id");
	int productRate = (int)session.getAttribute("productRate");
	int productQuantity = (int)session.getAttribute("productDetailQuantity");
	int prQuantity = 0;
	if(productQuantity>0){
		prQuantity = 1;
	}
	
	String productComment = (String)session.getAttribute("productComment");
	int productRateCount = (int) session.getAttribute("productRateCount");

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/frontend/css/jquery.fancybox.css?v=2.1.6\"\r\n");
      out.write("\ttype=\"text/css\" media=\"screen\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/frontend/js/jquery.fancybox.pack.js?v=2.1.6\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/frontend/css/jquery.fancybox-buttons.css?v=1.0.5\"\r\n");
      out.write("\ttype=\"text/css\" media=\"screen\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/frontend/js/jquery.fancybox-buttons.js?v=1.0.5\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/frontend/css/magiczoom.css\">\r\n");
      out.write("<script src=\"js/magiczoom.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$(\".fancybox\").fancybox({\r\n");
      out.write("\t\t\topenEffect : 'elastic',\r\n");
      out.write("\t\t\tcloseEffect : 'elastic',\r\n");
      out.write("\t\t\tprevEffect : 'none',\r\n");
      out.write("\t\t\tnextEffect : 'none',\r\n");
      out.write("\t\t\tcloseBtn : false,\r\n");
      out.write("\t\t\thelpers : {\r\n");
      out.write("\t\t\t\ttitle : {\r\n");
      out.write("\t\t\t\t\ttype : 'inside'\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tbuttons : {}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#img_large .MagicZoom\").click(function() {\r\n");
      out.write("\t\t\t$(\".view-large\").click();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<a\r\n");
      out.write("\thref=\"");
if (productDetailImg != null) {
	out.print(productDetailImg);
}
      out.write("\"\r\n");
      out.write("\tclass=\"fancybox view-large\" rel=\"gallery\" style=\"display: none;\"></a>\r\n");
      out.write("<div class=\"l-main-content\">\r\n");
      out.write("\t<div class=\"single-img\">\r\n");
      out.write("\t\t<div id=\"img_large\">\r\n");
      out.write("\t\t\t<a class=\"MagicZoom\" id=\"Zoomer\" rel=\"selectors-effect-speed: 600\"\r\n");
      out.write("\t\t\t\thref=\"");
if (productDetailImg != null) {
	out.print(productDetailImg);
}
      out.write("\"\r\n");
      out.write("\t\t\t\ttitle=\"Click để xem ảnh lớn\"> <img\r\n");
      out.write("\t\t\t\tsrc=\"");
if (productDetailImg != null) {
	out.print(productDetailImg);
}
      out.write("\"\r\n");
      out.write("\t\t\t\ttitle=\"Click để xem ảnh lớn\" alt=\"\" />\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end single-img-->\r\n");
      out.write("\t<div class=\"single-content\">\r\n");
      out.write("\t\t<div class=\"single-product-title\">\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t<h1>\r\n");
      out.write("\t\t\t\t");

					if (productDetailName != null) {
						out.print(productDetailName);
					}
				
      out.write("\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p class=\"product-code\">\r\n");
      out.write("\t\t\t\tMã sản phẩm :\r\n");
      out.write("\t\t\t\t");

				if (productDetailPrefix != null) {
					out.print(productDetailPrefix);
				}
			
      out.write("\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"infor-summary\">\r\n");
      out.write("\t\t\t<div class=\"product-price\">\r\n");
      out.write("\t\t\t\t");

					if (productDetailPrice > 0) {
						out.print(Utilities.convertMoney(productDetailPrice));
					} else {
						out.print("Liên hệ");
					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t\t<div class=\"product-vote\">\r\n");
      out.write("\t\t\tĐánh giá:\r\n");
      out.write("\t\t\t");

				for(int i = 1; i<=5 ; i++){
					if(i<=productRate){
						
      out.write(" <span class=\"star-o\"></span> ");

					}else{
						
      out.write("<span class=\"star-d\"></span>  ");

					}
				}
			
      out.write("\r\n");
      out.write("\t\t\t\t<span >(");
      out.print(productRateCount );
      out.write(" đánh giá)</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"product-warranty\">\r\n");
      out.write("\t\t\t\t<strong>Bảo hành: </strong>\r\n");
      out.write("\t\t\t\t");

					if (productDetailWarranty != null) {
						out.print(productDetailWarranty);
					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"product-summary\">\r\n");
      out.write("\t\t\t\t<strong>Mô tả ngắn: </strong>\r\n");
      out.write("\t\t\t\t<div class=\"product-content\">\r\n");
      out.write("\t\t\t\t\t");

						if (productDetailSummary != null) {
							out.print(productDetailSummary);
						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"bt-single-product\">\r\n");
      out.write("\t\t\t<a href=\"javascript:addToShoppingCart('pro','");
      out.print(product_id );
      out.write('\'');
      out.write(',');
      out.print(prQuantity );
      out.write(',');
      out.write('\'');
      out.print(productDetailPrice );
      out.write("')\" class=\"add-cart-checkout\" title=\"Đặt hàng\">Đặt\r\n");
      out.write("\t\t\t\thàng</a> <a href=\"javascript:addToShoppingCartStop('pro',");
      out.print(product_id );
      out.write(',');
      out.write('\'');
      out.print(prQuantity );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(productDetailPrice );
      out.write("')\" class=\"add-to-cart\" title=\"Cho\r\n");
      out.write("\t\t\t\tvào giỏ hàng\">Cho\r\n");
      out.write("\t\t\t\tvào giỏ hàng</a> <a href=\"#\" class=\"add-to-favorite\"\r\n");
      out.write("\t\t\t\ttitle=\"Đặt hàng\">Lưu sản phẩm</a>\r\n");
      out.write("\t\t\t<div class=\"single-advantage\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"product-detail\">\r\n");
      out.write("\t\t\t<div class=\"product-detail-title\">Mô tả chi tiết sản\r\n");
      out.write("\t\t\t\tphẩm</div>\r\n");
      out.write("\t\t\t<div class=\"product-detail-area\">\r\n");
      out.write("\t\t\t\t");

					if (productDetailContent != null) {
						out.print(productDetailContent);
					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"rate-area\">\r\n");
      out.write("\t\t\t<div class=\"product-detail-title\">Đánh giá sản phẩm</div>\r\n");
      out.write("\t\t\t");
if(productComment!=null){
				out.print(productComment);
			}
			
      out.write("\r\n");
      out.write("\t\t\t<div class=\"rate-content\">\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/ProductRating\" method=\"post\" accept-charset=\"utf-8\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"5\"><textarea\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"padding: 10px; line-height: 1.4\" name=\"comment\" id = \"comment\" cols=\"90\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\trows=\"5\" placeholder=\"Nội dung đánh giá\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"5\" align=\"left\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"color: #333; font-size: 14px; font-weight: bold\">Đánh giá :</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"radio\" id=\"rdoRate\" name=\"rdoRate\" value=\"5\" checked=\"checked\" placeholder=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"star-o\"></span> <span class=\"star-o\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"star-o\"></span> <span class=\"star-o\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"star-o\"></span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"radio\" id=\"rdoRate\" name=\"rdoRate\" value=\"4\" placeholder=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"star-o\"></span> <span class=\"star-o\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"star-o\"></span> <span class=\"star-o\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"star-d\"></span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"radio\" id=\"rdoRate\" name=\"rdoRate\" value=\"3\" placeholder=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"star-o\"></span> <span class=\"star-o\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"star-o\"></span> <span class=\"star-d\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"star-d\"></span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"radio\" id=\"rdoRate\" name=\"rdoRate\" value=\"2\" placeholder=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"star-o\"></span> <span class=\"star-o\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"star-d\"></span> <span class=\"star-d\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"star-d\"></span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"radio\" id=\"rdoRate\" name=\"rdoRate\" value=\"1\" placeholder=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"star-o\"></span> <span class=\"star-d\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"star-d\"></span> <span class=\"star-d\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"star-d\"></span></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"5\"><input class=\"btnRating\" type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"\" value=\"Đánh giá\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--End Rating-->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "ProductReferences.jsp", out, true);
      out.write("\r\n");
      out.write("\t\t<!-- end Product references -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end single-img-->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- end l-main-content-->\r\n");
      out.write("<div class=\"r-main-content\">\r\n");
      out.write("\t<div class=\"single-sidebar-title\">Hãng sản xuất</div>\r\n");
      out.write("\t<div class=\"sidebar-content\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\" title=\"\">Hãng khác(6)</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\" title=\"\">HIK VISION (8)</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\" title=\"\"> QUESTEK (1)</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--end sidebar-->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"single-sidebar-title\">Khoảng giá</div>\r\n");
      out.write("\t<div class=\"sidebar-content\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\" title=\"\">Dưới 5 triệu(10)</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\" title=\"\">5triệu đến 6 triệu(2)</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\" title=\"\">6 triệu đến 7 triệu(3)</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\" title=\"\">7 triệu đến 8 triệu(3)</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\" title=\"\">8 triệu đến 9 triệu(3)</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\" title=\"\">9 triệu đến 10 triệu(3)</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\" title=\"\">10 triệu đến 11 triệu(3)</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\" title=\"\">11 triệu đến 12 triệu(3)</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\" title=\"\">12 triệu đến 13 triệu(3)</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\" title=\"\">13 triệu đến 14 triệu(3)</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\" title=\"\">14 triệu đến 15 triệu(3)</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\" title=\"\">Trên 15 triệu(10)</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--end sidebar-->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- end r-main-content-->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
