/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2017-04-26 11:57:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.frontend;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "data.jsp", out, true);
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<title>Hùng Cường Computer</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/frontend/css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/frontend/css/font-awesome.min.css\">\r\n");
      out.write("\t<script language=\"javascript\" type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/frontend/js/jquery-1.8.2.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/frontend/js/owl.carousel.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/frontend/js/common.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<div class=\"tp-header\">\r\n");
      out.write("\t\t\t<div class=\"wrapper\">\r\n");
      out.write("\t\t\t\t<div class=\"l-tp-header\">\r\n");
      out.write("\t\t\t\t\t<a href=\"tel:0965909929\" title=\"Chăm sóc khách hàng\"><i class=\"fa fa-phone\" aria-hidden=\"true\"></i> Chăm sóc khách hàng: <span class=\"phone-number\">0965 909 929</span></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" title=\"Tải báo giá,hợp đồng\"><i class=\"fa fa-download\" aria-hidden=\"true\"></i> Tải báo giá,hợp đồng</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" title=\"Xây dựng cấu hình\"><i class=\"fa fa-laptop\" aria-hidden=\"true\"></i> Xây dựng cấu hình</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" title=\"Tin tức nổi bật\"><i class=\"fa fa-newspaper-o\" aria-hidden=\"true\"></i> Tin tức nổi bật</a>\r\n");
      out.write("\t\t\t\t</div><!-- end l-tp-header-->\r\n");
      out.write("\t\t\t\t<div class=\"r-tp-header\"></div><!-- end r-tp-header-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div><!-- end tp-header-->\r\n");
      out.write("\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t<div class=\"bt-header\">\r\n");
      out.write("\t\t\t<div class=\"wrapper\">\r\n");
      out.write("\t\t\t\t<div class=\"l-bt-header\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" title=\"Hùng cường Computer\">logo</a>\r\n");
      out.write("\t\t\t\t</div><!-- end l-bt-header-->\r\n");
      out.write("\t\t\t\t<div class=\"c-bt-header\">\r\n");
      out.write("\t\t\t\t\t<div class=\"slider-wrapper theme-default\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"slider\" class=\"nivoSlider\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/frontend/pictures/banner4.jpg\"  alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/frontend/pictures/banner1.jpg\"  alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/frontend/pictures/banner2.jpg\"  alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div><!--End .slider-wrapper-->\r\n");
      out.write("\t\t\t\t\t\t<script language=\"javascript\" type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/frontend/js/jquery.nivo.slider.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t$(window).load(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#slider').nivoSlider();\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t</div><!-- end c-bt-header-->\r\n");
      out.write("\t\t\t\t<div class=\"r-bt-header\">\r\n");
      out.write("\t\t\t\t\t<div class=\"login-area\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" title=\"Đăng nhập\"><i class=\"fa fa-user\" aria-hidden=\"true\"></i> Đăng nhập</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" title=\"Đăng nhập\"><i class=\"fa fa-user-plus\" aria-hidden=\"true\"></i> Đăng ký</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"cart-area\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" title=\"Giỏ hàng\"><i class=\"fa fa-shopping-cart\" aria-hidden=\"true\"></i> Giỏ hàng</a>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"cart-count\"><i class=\"fa fa-comment-o\" aria-hidden=\"true\"></i> <span class=\"count\">0<span></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div><!-- end r-bt-header-->\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clr\"></div>\r\n");
      out.write("\t\t</div><!-- end bt-header-->\r\n");
      out.write("\t</div><!-- end header-->\r\n");
      out.write("\t<div class=\"clr\"></div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
