/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2017-05-01 10:50:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.frontend;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.object.UserObject;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.object.UserObject");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "data.jsp", out, true);
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"utf-8\">\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("\t<title>Hùng Cường Computer</title>\n");
      out.write("\t<link rel=\"stylesheet\"\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/frontend/css/style.css\">\n");
      out.write("\t<link rel=\"stylesheet\"\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/frontend/css/single.css\">\n");
      out.write("\t<link rel=\"stylesheet\"\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/frontend/css/font-awesome.min.css\">\n");
      out.write("\t<link rel=\"stylesheet\"\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/frontend/css/bootstrap.css\">\n");
      out.write("\t<script language=\"javascript\" type=\"text/javascript\"\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/frontend/js/jquery-1.8.2.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/frontend/js/owl.carousel.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/frontend/js/common.js\"></script>\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/frontend/js/bootstrap.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"header\">\n");
      out.write("\t\t<div class=\"tp-header\">\n");
      out.write("\t\t\t<div class=\"wrapper\">\n");
      out.write("\t\t\t\t<div class=\"l-tp-header\">\n");
      out.write("\t\t\t\t\t<a href=\"tel:0965909929\" title=\"Chăm sóc khách hàng\"><i\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-phone\" aria-hidden=\"true\"></i> Chăm sóc khách hàng: <span\n");
      out.write("\t\t\t\t\t\tclass=\"phone-number\">0965 909 929</span></a> <a href=\"#\"\n");
      out.write("\t\t\t\t\t\ttitle=\"Tải báo giá,hợp đồng\"><i class=\"fa fa-download\"\n");
      out.write("\t\t\t\t\t\taria-hidden=\"true\"></i> Tải báo giá,hợp đồng</a> <a href=\"#\"\n");
      out.write("\t\t\t\t\t\ttitle=\"Xây dựng cấu hình\"><i class=\"fa fa-laptop\"\n");
      out.write("\t\t\t\t\t\taria-hidden=\"true\"></i> Xây dựng cấu hình</a> <a href=\"#\"\n");
      out.write("\t\t\t\t\t\ttitle=\"Tin tức nổi bật\"><i class=\"fa fa-newspaper-o\"\n");
      out.write("\t\t\t\t\t\taria-hidden=\"true\"></i> Tin tức nổi bật</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- end l-tp-header-->\n");
      out.write("\t\t\t\t<div class=\"r-tp-header\"></div>\n");
      out.write("\t\t\t\t<!-- end r-tp-header-->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- end tp-header-->\n");
      out.write("\t\t<div class=\"clr\"></div>\n");
      out.write("\t\t<div class=\"bt-header\">\n");
      out.write("\t\t\t<div class=\"wrapper\">\n");
      out.write("\t\t\t\t<div class=\"l-bt-header\">\n");
      out.write("\t\t\t\t\t<a href=\"#\" title=\"Hùng cường Computer\">logo</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- end l-bt-header-->\n");
      out.write("\t\t\t\t<div class=\"c-bt-header\">\n");
      out.write("\t\t\t\t\t<div class=\"slider-wrapper theme-default\">\n");
      out.write("\t\t\t\t\t\t<div id=\"slider\" class=\"nivoSlider\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><img\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/frontend/pictures/banner4.jpg\"\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\" /></a> <a href=\"#\"><img\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/frontend/pictures/banner1.jpg\"\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\" /></a> <a href=\"#\"><img\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/frontend/pictures/banner2.jpg\"\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\" /></a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--End .slider-wrapper-->\n");
      out.write("\t\t\t\t\t<script language=\"javascript\" type=\"text/javascript\"\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/frontend/js/jquery.nivo.slider.js\"></script>\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t\t\t\t$(window).load(function() {\n");
      out.write("\t\t\t\t\t\t\t$('#slider').nivoSlider();\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t</script>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- end c-bt-header-->\n");
      out.write("\t\t\t\t<div class=\"r-bt-header\">\n");
      out.write("\t\t\t\t\t<div class=\"login-area\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\t");

							UserObject userLogined = (UserObject) session.getAttribute("userLogined");
							if (userLogined != null && userLogined.getUser_permission_id()!=0) {
						
      out.write("\n");
      out.write("\t\t\t\t\t\t<a href=\"/WebBanHang/\" title=\"");
      out.print(userLogined.getUser_name());
      out.write("\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-user\" style=\"font-weight: bold;\" aria-hidden=\"true\"></i>\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(userLogined.getUser_name());
      out.write(" </a> <a\n");
      out.write("\t\t\t\t\t\t\thref=\"/WebBanHang/user/logout\" title=\"Thoát\"><i class=\"fa fa-sign-out\" aria-hidden=\"true\"></i> Thoát</a>\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0)\" title=\"Đăng nhập\" data-toggle=\"modal\" data-target=\"#mdLogin\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-user\" aria-hidden=\"true\"></i> Đăng nhập</a> <a href=\"#\"\n");
      out.write("\t\t\t\t\t\t\ttitle=\"Đăng ký\"><i class=\"fa fa-user-plus\" aria-hidden=\"true\"></i>\n");
      out.write("\t\t\t\t\t\t\tĐăng ký</a>\n");
      out.write("\t\t\t\t\t\t");

						
							}
						
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"cart-area\">\n");
      out.write("\t\t\t\t\t\t<a href=\"/WebBanHang/frontend/cart.jsp\" title=\"Giỏ hàng\"><i class=\"fa fa-shopping-cart\"\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\"></i> Giỏ hàng</a> <span class=\"cart-count\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-comment-o\" aria-hidden=\"true\"></i> <span\n");
      out.write("\t\t\t\t\t\t\tclass=\"count\" id=\"count_shopping_cart_store\">0<span></span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- end r-bt-header-->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"clr\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- end bt-header-->\n");
      out.write("\t</div>\n");
      out.write("\t<!-- end header-->\n");
      out.write("\t<div class=\"clr\"></div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
